#!/usr/bin/env bash
#MISE description="Cleanup Telegram cache"
#MISE hide=true
#MISE dir="."

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Quit Telegram ..."
osascript -e 'quit app "Telegram"'

print_header "Cleaning Telegram cache ..."
find "$HOME/Library/Group Containers/6N38VWS5BX.ru.keepcoder.Telegram/appstore" -type f -name "telegram-*" -size +1024k -delete

print_header "Starting Telegram ..."
open -a Telegram
