[dotfiles]

# 1Password
"~/.config/1Password/ssh/agent.toml" = { mode = "symlink", source = "1Password/agent.toml" }

# dprint & Taplo
"~/.config/dprint.json" = { mode = "symlink", source = "dprint/dprint.json" }
"~/.config/taplo.toml"  = { mode = "symlink", source = "dprint/taplo.toml" }

# fnox
"~/.config/fnox/config.toml" = { mode = "symlink", source = "fnox/fnox.toml" }

# Gem
"~/.gemrc" = { mode = "symlink", source = "gem/.gemrc" }

# Ghostty
"~/.config/ghostty/config" = { mode = "symlink", source = "ghostty/config" }

# Git & SSH
"~/.config/git" = { mode = "symlink-each", source = "git" }
"~/.ssh"        = { mode = "symlink-each", source = "ssh" }

# GitHub CLI
"~/.config/gh/config.yml" = { mode = "symlink", source = "github/config.yml" }

# Brewfile (casks + VS Code extensions, applied by brew:casks)
"~/.config/brewfile" = { mode = "symlink", source = "homebrew/brewfile" }

# Mise (user level)
"~/.config/mise" = { mode = "symlink", source = "mise" }

# oh-my-posh
"~/.config/oh-my-posh" = { mode = "symlink", source = "oh-my-posh" }

# PNPM
"~/Library/Preferences/pnpm/config.yaml" = { mode = "symlink", source = "pnpm/config.yaml" }
