#!/usr/bin/env zsh

##############################################################################
# macOS Setup - Install all the tools using homebrew
##############################################################################
#
# Description:
#   Installs all the tools on fresh laptop or even already setup laptop
#   This script requires homebrew so it will first detect whether it exists
#   and if it doesn't, it will install it and then install all tools
#
# Usage:
#   ./setup
#
# Steps (Tasks):
# - First check whether `brew` is installed, if not then install it
# - Check whether everything is fine with brew using `brew doctor` command
# - Check whether anything needs to be installed using `brew bundle check` command
# - Install all tools from `Brewfile` using `brew bundle install --upgrade` command, if needed
# - Use `stow` to create symlinks for dotfiles (if applicable)
#
# Note:
#   This script must be run from the repository root directory where the
#   Brewfile is located.
#
# Author: Viraj Patel
##############################################################################

readonly SUCCESS_EMOJI="✅"
readonly ERROR_EMOJI="🚫"
readonly SETTING_EMOJI="⚙️"
readonly INSTALL_EMOJI="🚀"
readonly PACKAGE_EMOJI="📦"
readonly CHECK_EMOJI="🩺"

if ! command -v brew &> /dev/null; then
  echo "${INSTALL_EMOJI} Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "${SUCCESS_EMOJI} Homebrew is already installed."
fi

# Turn off homebrew analytics
echo "${SETTING_EMOJI} Turning off Homebrew analytics..."
brew analytics off

# Check Homebrew health
echo "${CHECK_EMOJI} Checking Homebrew health..."
brew doctor

# Export HOMEBREW config
export HOMEBREW_CASK_OPTS="--appdir=${HOME}/Applications --fontdir=${HOME}/Library/Fonts"

echo ""
echo "${PACKAGE_EMOJI} Installing/updating packages from brewfile..."
brew bundle install \
  --upgrade \
  --force \
  --file=${HOME}/Projects/github.com/virajp/macos-setup/dotfiles/homebrew/brewfile

# Check if mise & stow are installed, if not then raise error and exit
if ! command -v mise &> /dev/null; then
  echo "${ERROR_EMOJI} ERROR: mise not found. Please install it first and then re-run the setup."
  exit 1
fi
if ! command -v stow &> /dev/null; then
  echo "${ERROR_EMOJI} ERROR: stow not found. Please install it first and then re-run the setup."
  exit 1
fi

echo ""
echo "${SETTING_EMOJI} Setting up dotfiles with stow..."
if command -v stow &> /dev/null; then
  mise --cd "${HOME}/Projects/github.com/virajp/macos-setup" run stow:install
  echo "${SUCCESS_EMOJI} Dotfiles symlinked successfully."
else
  echo "${ERROR_EMOJI} ERROR: stow not found. Skipping dotfiles setup."
  exit 1
fi

echo ""
echo "${SUCCESS_EMOJI} Setup complete!"
