#!/usr/bin/env zsh

# Update the Brewfile
echo "Updating the Brewfile ... "
brew bundle dump --all --force --describe --file=./Brewfile

# Print the diff
echo "Printing the diff ... "
git diff --color=always | diff-so-fancy
