#!/usr/bin/env bash
#MISE description="Validate git-config"
#MISE dir="."

#USAGE flag "--fix" help="Remove forbidden configs from local git-config"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header_wait "Validating git-config ... "

FIXIT=${usage_fix:-false}

# Forbidden local git config settings
FORBIDDEN="user\.name|user\.email|user\.signingkey|commit\.gpgsign|tag\.gpgsign|gpg\.format|gpg\.program|gpg\.ssh\.program";

# Forbidden configs that exists in git local config
LOCAL_CONFIG=$(git config --local --list | grep -E "^($FORBIDDEN)=" || true);

if [ ! -z "$LOCAL_CONFIG" ]; then
  if [ "$FIXIT" = "true" ]; then
    print_header "Fixing";
    for line in ${(f)LOCAL_CONFIG}; do
      key=${line%=*}
      print_wait "- removing $key ... "
      git config unset --local $key
      print_header "OK"
    done
    exit 0
  else
    print_error "ERROR";
    for line in ${(f)LOCAL_CONFIG}; do
      print_warn "- $line"
    done
    # print_error "Please use \`mise run code:git-config --fix\` to remove them";
    print_error "Please use \`mise run ${MISE_TASK_NAME} --fix\` to remove them";
    exit 1;
  fi
fi

print_ok
