#!/usr/bin/env bash
#MISE description="Run pre-commit hooks on all files"
#MISE hide=true

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Running pre-commit ..."
pre-commit run --config .config/pre-commit-config.yaml --all-files || true
