#!/usr/bin/env bash
#MISE description="Upgrade macOS updates"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading macOS updates ..."
sudo softwareupdate --install --all --restart
