#!/usr/bin/env bash
#MISE description="Open VSCode"
#MISE hide=true

#USAGE arg "<folder>" default="." help="Folder to open in VSCode"

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

if (( $+commands[code] )); then
  code "$MISE_ORIGINAL_CWD/$usage_folder"
else
  echo "VSCode is not installed or not in PATH."
  exit 1
fi
