#!/usr/bin/env bash
#MISE description="List startup items (LaunchAgents & LaunchDaemons)"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "LaunchAgents @ /Library/LaunchAgents ..."
ls -1 /Library/LaunchAgents | sort

print_header "LaunchDaemons @ /Library/LaunchDaemons ..."
ls -1 /Library/LaunchDaemons | sort

print_header "User LaunchAgents @ ~/Library/LaunchAgents ..."
ls -1 ~/Library/LaunchAgents | sort
