#!/usr/bin/env bash
#MISE hide=true
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

print_header "Getting all IP addresses ..."
ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sort | awk '{ sub(/inet6? (addr:)? ?/, ""); print }'
