#!/usr/bin/env bash
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Getting public IP address ..."
doggo --type A --query myip.opendns.com --nameserver resolver1.opendns.com --ipv4 --short
