#:schema https://fnox.jdx.dev/schema.json

# Nothing is exported to the shell
env = false
# If a secret is missing, this determines the behavior
if_missing = "error"

[providers.global]
prefix  = "global/"
service = "fnox"
type    = "keychain"

[secrets.GITHUB_API_TOKEN]
provider = "global"
value    = "GITHUB_API_TOKEN"

[profiles.brew.secrets.GITHUB_API_TOKEN]
env      = "exec"
provider = "global"
value    = "GITHUB_API_TOKEN"

[profiles.brew.secrets.HOMEBREW_GITHUB_API_TOKEN]
env      = "exec"
provider = "global"
value    = "GITHUB_API_TOKEN"

[profiles.context7.secrets.CONTEXT7_API_KEY]
env      = "exec"
provider = "global"
value    = "CONTEXT7_API_KEY"

[profiles.mempalace.secrets.HF_TOKEN]
env      = "exec"
provider = "global"
value    = "HF_TOKEN"
