#!/usr/bin/env bash
#MISE description="Cleanup .DS_Store files from the system"
#MISE hide=true
#MISE dir="."

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

# If no argument is passed, use the current directory ($PWD) instead of $HOME
FOLDER=${1:-$HOME}

print_header "Cleaning up .DS_Store files in $FOLDER ..."
find "$FOLDER" -type f -name '.DS_Store' -not -path '*/Library/*' -ls -delete 2>/dev/null || true
