#!/usr/bin/env bash
#MISE description="Upgrade all tools managed in the system"
#MISE depends=["init:dot"]
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

# Kill keyboxd (gpg) to ensure that stale keys are refreshed
gpgconf --kill all || true

# Set global Git configuration for GPG SSH signing
git config --global gpg.ssh.allowedSignersFile "$HOME/.ssh/allowed_signers"

# Check for Touch ID setup for sudo authentication
mise run upgrade:touch-id

# Upgrade mise first to ensure we have the latest features and fixes
print_header "Upgrading MISE ..."
brew upgrade --formulae mise

# Reshim mise to ensure all tools are available
print_header "Reshimming mise ..."
mise reshim

# Run mise doctor
print_header "Running mise doctor ..."
mise doctor --quiet --silent > /dev/null

# Install & upgrade mise
print_header "Setting up MISE ..."
mise install

print_header "Upgrading mise tools ..."
mise upgrade  || true

# Prune all unused versions of tools
print_header "Pruning unused versions of tools ..."
mise prune --yes

# Upgrade Homebrew and all installed packages
mise upgrade:brew

print_header "Disabling .DS_Store file creation on network drives ..."
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

print_header "Disabling .DS_Store file creation on USB drives ..."
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

mise run upgrade:npm

mise run cleanupDS ~/Projects

mise run upgrade:macos:download

mise run upgrade:ai

print_header "Setup complete!"
