#!/usr/bin/env bash
#MISE hide=true
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

print_header "Getting default gateway ..."
route -n get default | grep gateway | awk '{ print $2 }'
