[tools]
python = "3.14.7"
uv     = "0.12.21"

[settings]
# Python settings
pipx.uvx            = true
python.compile      = false
python.uv_venv_auto = "create|source"

[env]
# Python (uv)
UV_NO_CACHE          = "true"
UV_NO_MANAGED_PYTHON = "true"
UV_PYTHON_DOWNLOADS  = "never"
