#!/usr/bin/env zsh
#MISE hide=true

set -e
source "${0%/*}/_helpers"

print_header "Getting system information ..."
echo -e "\nYou are logged on $HOST"
echo -e "$NC "
system_profiler SPSoftwareDataType

print_subheader "\nAdditionnal information:$NC "
uname -a
echo -e "\nUsers logged on:$NC "
w -h
echo -e "\nCurrent date :$NC "
date
echo -e "\nMachine stats :$NC "
uptime
echo -e "\nCurrent network location :$NC "
scselect
echo -e "\nDNS Configuration:$NC "
scutil --dns

mise run ips:remoteip
