#!/usr/bin/env bash
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Getting IPv6 addresses ..."
ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | grep inet6 | awk '{ sub(/inet6? (addr:)? ?/, ""); print }'
