#!/usr/bin/env zsh
#MISE hide=true

set -e
source "${0%/*}/_helpers"

print_header "Getting public IP address ..."
doggo --type A --query myip.opendns.com --nameserver resolver1.opendns.com --ipv4 --short
