#!/usr/bin/env bash
#MISE description="Restart mempalace mcp"

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Restarting mempalace mcp ..."
mise x -- pitchfork restart global/mempalace-mcp
