#!/usr/bin/env bash
#MISE description="Restart qdrant (mempalace)"
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

print_header "Restarting qdrant (mempalace) ..."
mise run mempalace:stop
mise run mempalace:start
