#!/usr/bin/env zsh
#MISE description="Generate Brewfile"
#MISE hide=false

set -e
source "${0%/*}/_helpers"

print_header "Generating Brewfile ..."
brew bundle dump \
  --all \
  --force \
  --describe \
  --file "./Brewfile.gen"

print_header "Printing the diff ... "
git diff --no-index Brewfile.gen Brewfile | diff-so-fancy
