#!/usr/bin/env bash
#MISE description="Generate Brewfile"
#MISE hide=false

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Generating Brewfile ..."
brew bundle dump \
  --force \
  --describe \
  --file "./Brewfile.gen"

print_header "Printing the diff ... "
git diff --no-index Brewfile.gen Brewfile | diff-so-fancy
