#!/usr/bin/env zsh
#MISE description="Install packages from Brewfile"
#MISE hide=false

set -e
source "${0%/*}/_helpers"

print_header "Installing packages from Brewfile ..."
brew bundle install \
  --all \
  --upgrade \
  --force \
  --describe \
  --file "./Brewfile"

print_header "Cleaning up Homebrew cache ..."
brew cleanup --prune=all
