#!/usr/bin/env bash
#MISE description="Install packages from Brewfile"
#MISE hide=false

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Installing packages from Brewfile ..."
brew bundle install \
  --upgrade \
  --force \
  --file "~/brewfile"

print_header "Cleaning up Homebrew cache ..."
brew cleanup --prune=all
