#!/usr/bin/env bash
#MISE description="Setup / Upgrade AI tools"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading AI tools ..."

print_subheader "Adding marketplaces ..."
pnpx @askviraj/ai-plugins --all

print_subheader "Prune plugins ..."
claude plugin autoremove --scope user --yes
