#!/usr/bin/env bash
#MISE description="Upgrade all tools managed using Homebrew"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Homebrew packages ..."

# Check if brew is installed before attempting to update
if ! command -v brew >/dev/null 2>&1; then
  print_error "Homebrew is not installed. Please install Homebrew first."
  exit 1
fi

# Update Homebrew itself
print_subheader "Updating Homebrew ..."
brew update --force # --verbose

# Remove packages NOT in Brewfile
print_subheader "Deleting packages NOT in Brewfile ..."
brew bundle cleanup \
  --force \
  --verbose \
  --file "~/.config/brewfile"

# Install/Upgrade all packages from Brewfile
print_subheader "Install/Upgrade all packages from Brewfile ..."
brew bundle install \
  --upgrade \
  --force \
  --verbose \
  --file "~/.config/brewfile"

print_subheader "Upgrading all Homebrew packages ..."
brew upgrade --display-times --yes --formulae --force-bottle

# Remove unused dependencies
print_subheader "Removing unused Homebrew dependencies ..."
brew autoremove

# Cleanup old versions of packages
print_subheader "Cleaning up old Homebrew packages ..."
brew cleanup --prune=all
