#!/usr/bin/env bash
#MISE description="Upgrade gcloud components"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading gcloud components ..."
# Check if gcloud is installed before attempting to update
type gcloud >/dev/null 2>&1 || return 0
# Update gcloud components with quiet output to avoid unnecessary logs
gcloud components update --verbosity=warning --quiet
