#!/usr/bin/env bash
#MISE description="Upgrade grype database"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading grype database ..."
# Check if grype is installed before attempting to update
type grype >/dev/null 2>&1 || return 0
# Update grype database with quiet output to avoid unnecessary logs
grype db update
