#!/usr/bin/env bash
#MISE description="Upgrade pnpm"
#MISE hide=true
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

# Check if pnpm is installed before attempting to update
type pnpm >/dev/null 2>&1 || exit 0

# Upgrade global pnpm packages
print_subheader "Upgrading global pnpm packages ..."
pnpm upgrade --global
