#!/usr/bin/env bash
#MISE description="Upgrade macOS updates"
#MISE hide=true
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

print_header "Upgrading macOS updates ..."
sudo softwareupdate --install --all --restart
