# Packages to be installed via Homebrew
[bootstrap.packages]
# Formulaes
"brew:lcov" = "latest" # Code coverage tool for C/C++

# Casks
"brew-cask:android-studio"     = "latest" # Tools for building Android applications
"brew-cask:sublime-text"       = "latest" # Text editor for code, markup and prose
"brew-cask:visual-studio-code" = "latest" # Open-source code editor
# "brew-cask:lm-studio"          = "latest" # Discover, download, and run local LLMs

# Mac App Store (keyed by ADAM id)
"mas:1450874784" = "latest" # Transporter
"mas:497799835"  = "latest" # Xcode
"mas:640199958"  = "latest" # Developer
"mas:899247664"  = "latest" # TestFlight

# Developer Tools
[tools.bun]
version = "latest"

[dotfiles]
# dprint & Taplo
"~/.config/dprint.json" = {}
"~/.config/taplo.toml"  = {}

# Gem
"~/.gemrc" = {}

[env]
# Development tools
CHROME_EXECUTABLE           = "${HOME}/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"
DOTNET_CLI_TELEMETRY_OPTOUT = "true"
PRE_COMMIT_HOME             = "${HOME}/.cache/pre-commit"
RUNTIME_ENV                 = "development"

[shell_alias]
edit = "subl"
