[settings]
# Python, pipx, uv settings
# every pipx: tool installs through uv
pipx.uvx            = true
python.compile      = false
python.uv_venv_auto = "create|source"

[tools.python]
version = "latest"

[tools.uv]
depends = [ "python" ]
version = "latest"

[env]
# Python (uv)
UV_NO_CACHE          = true
UV_NO_MANAGED_PYTHON = true
UV_PYTHON_DOWNLOADS  = "never"
