[settings]
# arch = "x86_64"
activate_aggressive = true
all_compile         = false
env_shell_expand    = true
gpg_verify          = true
paranoid            = true
task_output         = "interleave"

[tools]
dprint     = { version = "latest" }
node       = { postinstall = "npm uninstall --global npm", version = "latest" }
pnpm       = { version = "latest" }
pre-commit = { version = "latest" }
taplo      = { version = "latest" }

[env]
HOMEBREW_BUNDLE_FILE = "./Brewfile"

[tasks.init]
description = "Initialize mise tasks"
hide        = true
run         = "find $MISE_ORIGINAL_CWD/.config/mise/tasks/ -name '*' -type f -exec chmod 755 {} \\;"

[shell_alias]
lint  = "mise run lint"
setup = "mise run setup:all"
