[settings]
# arch = "x86_64"
all_compile = false
activate_aggressive = true
paranoid = true
gpg_verify = true
task_output = "interleave"
env_shell_expand = true

[env]
HOMEBREW_BUNDLE_FILE="./Brewfile"

[tasks]

# Precommit
[tasks."precommit"]
description = "Run pre-commit hooks on all files"
run = "pre-commit run --all-files"

[tasks."setup:precommit"]
description = "Setup pre-commit hooks"
run = """
  echo "Updating pre-commit hooks ..."
  pre-commit autoupdate

  echo "Installing pre-commit ..."
  pre-commit install --all --install-hooks
  """

# Lint
[tasks."lint"]
description = "Linting, formatting"
run = """
  echo "YAML linting, formatting ..."
  npx prettier --config ./.prettierrc.yaml --check --write "**/*.yaml"
  echo "Markdown linting, formatting ..."
  npx markdownlint-cli2 --fix --format "**/*.md" "#node_modules"
  """

# Dotfiles tasks
[tasks."stow:install"]
description = "Install dotfiles using stow"
dir = "dotfiles"
run = """
  find . -type f -name '.DS_Store' -ls -delete
  stow --dir=. --target=$HOME --verbose */
  """

[tasks."stow:reinstall"]
description = "Re-install dotfiles using stow"
dir = "dotfiles"
run = """
  find . -type f -name '.DS_Store' -ls -delete
  stow --restow --dir=. --target=$HOME --verbose */
  """

[tasks."stow:cleanup"]
description = "Cleanup dotfiles using stow"
dir = "dotfiles"
run = "stow --delete --dir=. --target=$HOME --verbose */"

[tasks."stow:simulate"]
description = "Simulate dotfiles using stow"
dir = "dotfiles"
run = "stow --dir=. --target=$HOME --verbose --simulate */"

# Brewfile tasks
[tasks."brew:gen"]
description = "Generate brewfile for all installed packages"
run = """
  echo "Generating brewfile ..."
  brew bundle dump --all --force --describe
  echo "Printing the diff ... "
  git diff --color=always | diff-so-fancy
  """

[tasks."brew:check"]
description = "Check installed packages against brewfile"
run = """
  # Check installed packages against brewfile
  echo "Listing packages not in Brewfile ..."
  brew bundle check --describe
  """

[tasks."brew:install"]
description = "Install packages in brewfile"
run = """
  echo "Install packages in Brewfile ..."
  brew bundle install --describe --verbose
  """

[tasks."brew:cleanup"]
description = "Remove packages not in brewfile"
run = """
  echo "Removing packages not in Brewfile ..."
  brew bundle cleanup --force --describe
  echo "Autoremoving packages ..."
  brew autoremove --verbose
  """

[shell_alias]
lint = "mise run lint"
