#!/usr/bin/env bash
#MISE description="Setup / Upgrade AI tools"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading AI tools ..."

print_subheader "Linking Claude Code to ~/.local/bin/claude ..."
mkdir -p ~/.local/bin
ln -sf "$(mise which claude)" ~/.local/bin/claude

print_subheader "Adding marketplaces ..."
pnpx @askviraj/ai-plugins --all --upgrade --yes --skip-graphify

print_subheader "Prune plugins ..."
claude plugin autoremove --scope user --yes
