#!/usr/bin/env bash
#MISE description="Upgrade all tools managed using Homebrew"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Upgrading Homebrew and all installed packages ..."

# Check if brew is installed before attempting to update
type brew >/dev/null 2>&1 || return 0

# Update Homebrew itself
brew update --auto-update --force # --verbose

# Upgrade all installed formulaes
print_subheader "Upgrading Homebrew formulaes ..."
brew upgrade \
  --force-bottle \
  --overwrite \
  --display-times \
  --formulae || print_success "All formulaes are up to date!"

# Upgrade all installed casks
print_subheader "Upgrading Homebrew casks ..."
brew upgrade \
  --display-times \
  --greedy \
  --casks || print_success "All casks are up to date!"

# Remove unused dependencies
print_subheader "Removing unused Homebrew dependencies ..."
brew autoremove

# Cleanup old versions of packages
print_subheader "Cleaning up old Homebrew packages ..."
brew cleanup --prune=all
