#!/usr/bin/env bash
#MISE description="Check if Touch ID is configured for sudo authentication"
#MISE hide=true

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_separator "="
print_wait "Checking Touch ID setup for shell ... "

if grep -q "pam_tid.so" /etc/pam.d/sudo; then
  print_success "OK"
  exit 0
else
  print_error "NOT OK"
  echo "Please run the following commands to setup Touch ID for sudo:"
  print_success "subl /etc/pam.d/sudo"
  echo ""
  echo "Add the following line to the top of the file:"
  print_success "'auth       sufficient     pam_tid.so'"
  echo ""
  exit 1
fi
