#!/usr/bin/env bash
#MISE description="Create symlinks for stow-managed dotfiles"
#MISE hide=false
#MISE dir="dotfiles"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

find . -type f -name '.DS_Store' -ls -delete || true

print_header "Stowing dotfiles ..."
stow --dir=. --target=$HOME --verbose */
