#!/usr/bin/env bash
#MISE description="Recreate symlinks for stow-managed dotfiles"
#MISE hide=false
#MISE dir="dotfiles"
#MISE depends=["stow:prep"]

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Reinstalling stow-managed dotfiles ..."
stow --restow --dir=. --dotfiles --target=$HOME --verbose */
