#!/usr/bin/env bash
#MISE description="Recreate symlinks for stow-managed dotfiles"
#MISE hide=false
#MISE dir="dotfiles"
#MISE depends=["stow:prep"]

#USAGE arg "[tool]" help="Only reinstall specific tool's dotfiles"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Reinstalling stow-managed dotfiles (${usage_tool:-all}) ..."
stow --restow --dir=. --target=$HOME --verbose ${usage_tool:-*/}
