#!/usr/bin/env bash
#MISE description="Simulate creation of symlinks for stow-managed dotfiles"
#MISE hide=false
#MISE dir="dotfiles"
#MISE depends=["stow:prep"]

#USAGE arg "[tool]" help="Only simulate specific tool's dotfiles"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Simulating stow-managed dotfiles (${usage_tool:-all}) ..."
stow --dir=. --target=${HOME} --verbose --simulate ${usage_tool:-*/}
