#!/usr/bin/env bash
#MISE description="Simulate creation of symlinks for stow-managed dotfiles"
#MISE hide=false
#MISE dir="dotfiles"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

find . -type f -name '.DS_Store' -ls -delete || true

print_header "Simulating stow-managed dotfiles ..."
stow --dir=. --target=$HOME --verbose --simulate */
