#!/usr/bin/env bash
#MISE description="Stop the mempalace stack"
#MISE dir="~"

set -e
source "${HOME}/.config/mise/tasks/_scripts/helpers"

line_sep "="
print_warn "Stopping qdrant (mempalace) ... "
mise x --silent -- docker compose --file "${HOME}/.config/mempalace/docker-compose.yaml" down

print_wait "Stopping mempalace hub ... "
mise x --silent -- launchctl stop dev.mise.mempalace-hub && print_success
