#!/usr/bin/env bash
#MISE description="Delete symlinks for dotfiles"
#MISE hide=false
#MISE dir="dotfiles"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Deleting symlinks for dotfiles ..."
mise bootstrap dotfiles unapply --yes
