#!/usr/bin/env bash
#MISE description="Create symlinks for dotfiles"
#MISE hide=false
#MISE dir="dotfiles"
#MISE depends=["dotfiles:prep"]

#USAGE flag "--force" help="Force the creation of symlinks even if they already exist"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Setup dotfiles ..."
if [[ "${usage_force:-false}" == "true" ]]; then
    mise bootstrap dotfiles apply --yes --force
else
    mise bootstrap dotfiles apply --yes
fi
