#!/usr/bin/env bash
#MISE description="Show status of dotfiles"
#MISE hide=false
#MISE dir="dotfiles"
#MISE depends=["dotfiles:prep"]

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Showing status of dotfiles (${usage_tool:-all}) ..."
mise bootstrap dotfiles status --missing
