color = "green"
name  = "Incident Guardian" # label in the + menu
title = "Incident Guardian" # the tab title you're after

[[panes]]
directory = "~/Projects/gitlab.com/dnl/incident-guardian"
id        = "main"
type      = "terminal"
