color = "green"
name  = "IG (Claude)" # label in the + menu
title = "IG (Claude)" # the tab title you're after

[[panes]]
commands  = [ "cc --continue" ]
directory = "~/Projects/gitlab.com/dnl/incident-guardian"
id        = "main"
type      = "terminal"
