#!/usr/bin/env zsh
#MISE description="Lint & format on all files"
#MISE hide=false

set -e
source "${0%/*}/_helpers"

print_header "YAML linting, formatting ..."
npx prettier --write --ignore-unknown --log-level error --config ./.prettierrc.yaml '**/*.{md,yaml,yml}'

print_header "Markdown linting, formatting ..."
npx markdownlint-cli2 --fix "**/*.md" "#dotfiles/claude/.claude" "#.claude"
