[providers]
keychain = { service = "fnox", type = "keychain" }

[secrets]
CONTEXT7_API_KEY          = { provider = "keychain", value = "global/CONTEXT7_API_KEY" }
GITHUB_API_TOKEN          = { provider = "keychain", value = "global/GITHUB_API_TOKEN" }
HOMEBREW_GITHUB_API_TOKEN = { provider = "keychain", value = "global/GITHUB_API_TOKEN" }
